name: Call Run PowerShell Script Template e213ff0f-5d5c-4791-802d-52ea3e7be1f1

on:
  push:
    branches: [ main, feature/dk* ]

jobs:
  run-ps-script:
    uses: kiranvattikuti146/POWERSHELL-REUSABLE-V2/.github/workflows/reusable.yml@main
    with:
      targetType: inlineScript
      filePath: 'scripts/sample-script.ps1'
      arguments: 'arg1 arg2'
      script: hostname
      workingFolder: '.'
      errorPreference: Stop
      ignoreLASTEXITCODE: false
