name: Call Run PowerShell Script Template e213ff0f-5d5c-4791-802d-52ea3e7be1f1

on:
  push:
    branches: [ main , feature/dk*]
  # workflow_dispatch:
  #   inputs:
  #     run:
  #       description: "Should this workflow run?"
  #       required: true
  #       default: "yes"

jobs:
  run-ps-script:
    # if: github.event_name == 'workflow_dispatch' && inputs.run == 'yes' 
    uses: kiranvattikuti146/POWERSHELL-REUSABLE/.github/workflows/reusable.yml@main
    with:
      scriptType: inlineScript #filePath
      scriptName: 'scripts/sample-script.ps1'
      arguments: 'arg1  arg2 '
      workingFolder: '.'
      # #inlineScript: # string. Required when scriptType = inlineScript. Inline Script.
      inlineScript: |
         Write-Host 'Hello, this is an inline script!'
         Write-Host 'Running some PowerShell commands...'
      failOnStandardError: true
